### ISSUE TITLE
Google Pocket?

### ISSUE THREAD

**Issue by benregn** [kn9ts/sepiarize#1]
Just out of curiosity, what is Google Pocket? Are you talking about https://getpocket.com?

**Comment by kn9ts** [comment]
Yes I am talking about that.

**Comment by benregn** [comment]
Ok, still unsure what Google Pocket is. Would you mind pointing me to something about it? :smiley:

**Comment by kn9ts** [comment]
If you know [Readiblity](https://www.readability.com/), which was the the 1st of it's kind before Google went ahead with photocopying the idea. It basically takes aritcles/blog posts' content you plan to read, and display it in a distraction free page with light, sepia and dark scheme options for your ease of reading preference.

Since they have been saved. You can opt to also read them later, or repeatedly after. Distraction free.

**Comment by benregn** [comment]
I've heard about [readability.com](https://www.readability.com/) (might even have used them at some point) and I'm familiar with the concept in general but I haven't heard, seen or been able to find anything which is called Google Pocket. I only know of [getpocket.com](https://getpocket.com) which has light, sepia and dark color schemes.

**Comment by kn9ts** [comment]
Hehehe!! Yes, and that is the one am talking about. It is owned by Google. Some people, like me, call it that.

**Comment by benregn** [comment]
Ok, you had me totally confused there :) I have never seen it called that. 

I can't find anything pointing to Google ownership other than Google Ventures investment participation in Pocket's Series A round (which is not the same as Google owning them). Also before Pocket was Pocket it was called Read it later which came out in 2007 before Readablitiy which came out in 2009.
